{% set version = "0.7.0" %}

package:
  name: label-maker
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/l/label-maker/label-maker-{{ version }}.tar.gz
  sha256: 35fc76863c6518bf00d86c22b3d3325e8563b92e0061adfcdc574fc35e2cf6ee

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  entry_points:
    - label-maker=label_maker.main:cli

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy >=1.13.3
    - cerberus >=1.1
    - click >=6.7
    - geojson >=2.3.0
    - homura >=0.1.5
    - humanize >=0.5.1
    - mercantile >=1.0.0
    - olefile >=0.44
    - pillow >=4.3.0
    - protobuf >=3.5.0.post1
    - pyclipper >=1.0.6
    - pycurl >=7.43.0.1
    - pyproj >=1.9.5.1
    - rasterio >=1.0a12
    - requests >=2.20.0
    - shapely >=1.6.3
    - six >=1.10.0
    - mapbox-vector-tile >=1.2.0
    - mbutil >=0.3.0
    - tilepie >=0.2.1

test:
  imports:
    - label_maker
  commands:
    - label-maker --help

about:
  home: https://github.com/developmentseed/label-maker/
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Data preparation for satellite machine learning
  dev_url: https://github.com/developmentseed/label-maker

extra:
  recipe-maintainers:
    - rluria14
    - benhuff
    - oblute
